spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  autoconfigure: # JPA 자동설정 끄기
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
